<?php
// Register custom fields programmatically for the One-Pager Affiliate Landing Page Plugin

function opalp_register_custom_fields() {
    if (function_exists('acf_add_local_field_group')) {
        // Dynamically build choices for payment images checkbox
        $payment_images_dir = plugin_dir_path(__FILE__) . '../assets/payments-images/';
        $payment_images_choices = array();
        if (is_dir($payment_images_dir)) {
            foreach (scandir($payment_images_dir) as $file) {
                if (is_file($payment_images_dir . $file) && preg_match('/\.(png|jpe?g|gif)$/i', $file)) {
                    $payment_images_choices[$file] = $file;
                }
            }
        }

        acf_add_local_field_group(array(
            'key' => 'group_one_pager_fields',
            'title' => 'One-Pager Fields',
            'fields' => array(
                // Tab for Top Header settings
                array(
                    'key'   => 'tab_top_header',
                    'label' => 'Top Header',
                    'type'  => 'tab',
                    'placement' => 'top',
                ),
                // Group for Header Bar Content
                array(
                    'key' => 'group_header_bar_content',
                    'label' => 'Header Bar Content',
                    'name' => 'header_bar_content',
                    'type' => 'group',
                    'instructions' => 'Settings for the top notification bar.',
                    'layout' => 'block', // Or 'table' or 'row'
                    'sub_fields' => array(
                        array(
                            'key' => 'field_top_header_text_string',
                            'label' => 'Top Header Text String',
                            'name' => 'top_header_text_string',
                            'type' => 'text',
                            'instructions' => 'Enter the text to display in the top header bar (optional).',
                            'wrapper' => array(
                                'width' => '50',
                            ),
                        ),
                        array(
                            'key' => 'field_countdown_date',
                            'label' => 'Countdown End Date',
                            'name' => 'countdown_date',
                            'type' => 'date_picker',
                            'instructions' => 'Select the date the countdown should end (optional).',
                            'display_format' => 'Y-m-d',
                            'return_format' => 'Y-m-d',
                            'wrapper' => array(
                                'width' => '25',
                            ),
                        ),
                        array(
                            'key' => 'field_show_visitor_count_top_header',
                            'label' => 'Show Visitor Count',
                            'name' => 'show_visitor_count_in_top_header',
                            'type' => 'true_false',
                            'instructions' => 'Display live visitor count in the top bar?',
                            'ui' => 1,
                            'wrapper' => array(
                                'width' => '25',
                            ),
                        ),
                    )
                ),
                array(
                    'key' => 'field_header_logo',
                    'label' => 'Header Logo',
                    'name' => 'header_logo',
                    'type' => 'image',
                    'instructions' => 'Upload the logo for the header.',
                    'return_format' => 'url',
                ),
                // Tab for Hero Section
                array(
                    'key'   => 'tab_hero_section',
                    'label' => 'Hero Section',
                    'type'  => 'tab',
                    'placement' => 'top',
                ),
                // Hero Section Fields (left column)
                array(
                    'key' => 'field_hero_video_file',
                    'label' => 'Hero Video File',
                    'name' => 'hero_video_file',
                    'type' => 'file',
                    'instructions' => 'Upload the MP4 file for the hero video.',
                    'return_format' => 'url',
                    'mime_types' => 'mp4',
                ),
                array(
                    'key' => 'field_hero_video_url',
                    'label' => 'Hero Video URL',
                    'name' => 'hero_video_url',
                    'type' => 'url',
                    'instructions' => 'Enter the YouTube URL for the hero video.',
                ),
                array(
                    'key' => 'field_fallback_hero_image',
                    'label' => 'Fallback Hero Image',
                    'name' => 'fallback_hero_image',
                    'type' => 'image',
                    'instructions' => 'Upload an image to display if no hero video is provided.',
                    'return_format' => 'url',
                ),
                array(
                    'key' => 'field_video_description',
                    'label' => 'Video Description',
                    'name' => 'video_description',
                    'type' => 'textarea',
                    'instructions' => 'Enter a description for the video.',
                ),
                // Hero Section Fields (right column)
                array(
                    'key' => 'field_product_name',
                    'label' => 'Product Name',
                    'name' => 'product_name',
                    'type' => 'text',
                    'instructions' => 'Enter the product name.',
                ),
                array(
                    'key' => 'field_product_rating',
                    'label' => 'Product Rating',
                    'name' => 'product_rating',
                    'type' => 'number',
                    'instructions' => 'Set the product rating (1 to 5, with up to one decimal place).',
                    'min' => 1,
                    'max' => 5,
                    'step' => 0.1,
                ),
                array(
                    'key' => 'field_number_of_reviews',
                    'label' => 'Number of Reviews',
                    'name' => 'number_of_reviews',
                    'type' => 'number',
                    'instructions' => 'Enter the number of reviews for the product.',
                    'min' => 0,
                    'step' => 1,
                ),
                array(
                    'key' => 'field_headline',
                    'label' => 'Headline',
                    'name' => 'headline',
                    'type' => 'text',
                    'instructions' => 'Enter the headline.',
                ),
                array(
                    'key' => 'field_subheadline',
                    'label' => 'Subheadline',
                    'name' => 'subheadline',
                    'type' => 'text',
                    'instructions' => 'Enter the subheadline.',
                ),
                array(
                    'key' => 'field_price',
                    'label' => 'Price',
                    'name' => 'price',
                    'type' => 'number',
                    'instructions' => 'Enter the product price.',
                    'min' => 0,
                    'step' => 0.01,
                    'wrapper' => array(
                        'width' => '33',
                    ),
                ),
                array(
                    'key' => 'field_discount_price',
                    'label' => 'Discount Price',
                    'name' => 'discount_price',
                    'type' => 'number',
                    'instructions' => 'Enter the discount price (if applicable).',
                    'min' => 0,
                    'step' => 0.01,
                    'wrapper' => array(
                        'width' => '33',
                    ),
                ),
                array(
                    'key' => 'field_bonus_offer_text',
                    'label' => 'Bonus Offer Text',
                    'name' => 'bonus_offer_text',
                    'type' => 'text',
                    'instructions' => 'Enter the bonus offer text to display alongside the price (optional).',
                    'wrapper' => array(
                        'width' => '33',
                    ),
                ),
                array(
                    'key' => 'field_button_1_text',
                    'label' => 'Button 1 Text',
                    'name' => 'button_1_text',
                    'type' => 'text',
                    'instructions' => 'Enter the text for the first call-to-action button.',
                ),
                array(
                    'key' => 'field_button_1_url',
                    'label' => 'Button 1 URL',
                    'name' => 'button_1_url',
                    'type' => 'url',
                    'instructions' => 'Enter the URL for the first call-to-action button.',
                ),
                array(
                    'key' => 'field_payment_images',
                    'label' => 'Payment Images',
                    'name' => 'payment_images',
                    'type' => 'checkbox',
                    'instructions' => 'Select payment images to display.',
                    'choices' => $payment_images_choices,
                    'layout' => 'horizontal',
                ),
                array(
                    'key' => 'field_money_back_days',
                    'label' => 'Days for Money Back Guarantee',
                    'name' => 'money_back_days',
                    'type' => 'number',
                    'instructions' => 'Enter the number of days for the money-back guarantee.',
                    'min' => 0,
                ),
                array(
                    'key' => 'field_blurb_1_icon_class',
                    'label' => 'Blurb 1 Icon Class',
                    'name' => 'blurb_1_icon_class',
                    'type' => 'text',
                    'instructions' => 'Enter the CSS class for the blurb icon (e.g., Font Awesome class).',
                ),
                array(
                    'key' => 'field_blurb_1_title',
                    'label' => 'Blurb 1 Title',
                    'name' => 'blurb_1_title',
                    'type' => 'text',
                    'instructions' => 'Enter the title for the first blurb.',
                ),
                array(
                    'key' => 'field_blurb_1_text',
                    'label' => 'Blurb 1 Text',
                    'name' => 'blurb_1_text',
                    'type' => 'textarea',
                    'instructions' => 'Enter the text for the first blurb.',
                ),
                array(
                    'key' => 'field_blurb_2_icon_class',
                    'label' => 'Blurb 2 Icon Class',
                    'name' => 'blurb_2_icon_class',
                    'type' => 'text',
                    'instructions' => 'Enter the CSS class for the second blurb icon (e.g., Font Awesome class).',
                ),
                array(
                    'key' => 'field_blurb_2_title',
                    'label' => 'Blurb 2 Title',
                    'name' => 'blurb_2_title',
                    'type' => 'text',
                    'instructions' => 'Enter the title for the second blurb.',
                ),
                array(
                    'key' => 'field_blurb_2_text',
                    'label' => 'Blurb 2 Text',
                    'name' => 'blurb_2_text',
                    'type' => 'textarea',
                    'instructions' => 'Enter the text for the second blurb.',
                ),
                array(
                    'key' => 'field_blurb_3_icon_class',
                    'label' => 'Blurb 3 Icon Class',
                    'name' => 'blurb_3_icon_class',
                    'type' => 'text',
                    'instructions' => 'Enter the CSS class for the third blurb icon (e.g., Font Awesome class).',
                ),
                array(
                    'key' => 'field_blurb_3_title',
                    'label' => 'Blurb 3 Title',
                    'name' => 'blurb_3_title',
                    'type' => 'text',
                    'instructions' => 'Enter the title for the third blurb.',
                ),
                array(
                    'key' => 'field_blurb_3_text',
                    'label' => 'Blurb 3 Text',
                    'name' => 'blurb_3_text',
                    'type' => 'textarea',
                    'instructions' => 'Enter the text for the third blurb.',
                ),
                array(
                    'key' => 'field_testimonial_1_text',
                    'label' => 'Testimonial 1 Text',
                    'name' => 'testimonial_1_text',
                    'type' => 'textarea',
                    'instructions' => 'Enter the text for the first testimonial.',
                ),
                array(
                    'key' => 'field_testimonial_1_author',
                    'label' => 'Testimonial 1 Author',
                    'name' => 'testimonial_1_author',
                    'type' => 'text',
                    'instructions' => 'Enter the author name for the first testimonial.',
                ),
                array(
                    'key' => 'field_testimonial_1_image',
                    'label' => 'Testimonial 1 Author Image',
                    'name' => 'testimonial_1_image',
                    'type' => 'image',
                    'instructions' => 'Upload the image for the first testimonial author.',
                    'return_format' => 'url',
                ),
                array(
                    'key' => 'field_testimonial_2_text',
                    'label' => 'Testimonial 2 Text',
                    'name' => 'testimonial_2_text',
                    'type' => 'textarea',
                    'instructions' => 'Enter the text for the second testimonial.',
                ),
                array(
                    'key' => 'field_testimonial_2_author',
                    'label' => 'Testimonial 2 Author',
                    'name' => 'testimonial_2_author',
                    'type' => 'text',
                    'instructions' => 'Enter the author name for the second testimonial.',
                ),
                array(
                    'key' => 'field_testimonial_2_image',
                    'label' => 'Testimonial 2 Author Image',
                    'name' => 'testimonial_2_image',
                    'type' => 'image',
                    'instructions' => 'Upload the image for the second testimonial author.',
                    'return_format' => 'url',
                ),
                array(
                    'key' => 'field_testimonial_3_text',
                    'label' => 'Testimonial 3 Text',
                    'name' => 'testimonial_3_text',
                    'type' => 'textarea',
                    'instructions' => 'Enter the text for the third testimonial.',
                ),
                array(
                    'key' => 'field_testimonial_3_author',
                    'label' => 'Testimonial 3 Author',
                    'name' => 'testimonial_3_author',
                    'type' => 'text',
                    'instructions' => 'Enter the author name for the third testimonial.',
                ),
                array(
                    'key' => 'field_testimonial_3_image',
                    'label' => 'Testimonial 3 Author Image',
                    'name' => 'testimonial_3_image',
                    'type' => 'image',
                    'instructions' => 'Upload the image for the third testimonial author.',
                    'return_format' => 'url',
                ),
                array(
                    'key' => 'field_comparison_chart_image',
                    'label' => 'Comparison Chart Image',
                    'name' => 'comparison_chart_image',
                    'type' => 'image',
                    'instructions' => 'Upload the image for the comparison chart.',
                    'return_format' => 'url',
                ),
                array(
                    'key' => 'field_section_1_title',
                    'label' => 'Section 1 Title',
                    'name' => 'section_1_title',
                    'type' => 'text',
                    'instructions' => 'Enter the title for the first common section.',
                ),
                array(
                    'key' => 'field_section_1_paragraph',
                    'label' => 'Section 1 Paragraph',
                    'name' => 'section_1_paragraph',
                    'type' => 'wysiwyg',
                    'instructions' => 'Enter the paragraph text for the first common section.',
                    'tabs' => 'all',
                    'toolbar' => 'full',
                    'media_upload' => true,
                ),
                array(
                    'key' => 'field_section_1_image',
                    'label' => 'Section 1 Image',
                    'name' => 'section_1_image',
                    'type' => 'image',
                    'instructions' => 'Upload the image for the first common section.',
                    'return_format' => 'url',
                ),
                array(
                    'key' => 'field_section_2_image',
                    'label' => 'Section 2 Image',
                    'name' => 'section_2_image',
                    'type' => 'image',
                    'instructions' => 'Upload the image for the second common section.',
                    'return_format' => 'url',
                ),
                array(
                    'key' => 'field_section_2_title',
                    'label' => 'Section 2 Title',
                    'name' => 'section_2_title',
                    'type' => 'text',
                    'instructions' => 'Enter the title for the second common section.',
                ),
                array(
                    'key' => 'field_section_2_paragraph',
                    'label' => 'Section 2 Paragraph',
                    'name' => 'section_2_paragraph',
                    'type' => 'wysiwyg',
                    'instructions' => 'Enter the paragraph text for the second common section.',
                    'tabs' => 'all',
                    'toolbar' => 'full',
                    'media_upload' => true,
                ),
                // Add As Seen On tab and fields
                array(
                    'key'   => 'tab_as_seen_on',
                    'label' => 'As Seen On',
                    'type'  => 'tab',
                    'placement' => 'top',
                ),
                array(
                    'key'           => 'field_as_seen_on_title',
                    'label'         => 'H2 Title',
                    'name'          => 'as_seen_on_title',
                    'type'          => 'text',
                    'instructions'  => 'Heading for the As Seen On section.',
                    'default_value' => 'As Seen On',
                ),
                array(
                    'key'           => 'field_as_seen_on_image_1',
                    'label'         => 'Image 1',
                    'name'          => 'as_seen_on_image_1',
                    'type'          => 'image',
                    'instructions'  => 'Upload the first As Seen On logo.',
                    'return_format' => 'url',
                ),
                array(
                    'key'           => 'field_as_seen_on_image_2',
                    'label'         => 'Image 2',
                    'name'          => 'as_seen_on_image_2',
                    'type'          => 'image',
                    'instructions'  => 'Upload the second As Seen On logo.',
                    'return_format' => 'url',
                ),
                array(
                    'key'           => 'field_as_seen_on_image_3',
                    'label'         => 'Image 3',
                    'name'          => 'as_seen_on_image_3',
                    'type'          => 'image',
                    'instructions'  => 'Upload the third As Seen On logo.',
                    'return_format' => 'url',
                ),
                array(
                    'key'   => 'tab_short_product_about',
                    'label' => 'Short Product About',
                    'type'  => 'tab',
                    'placement' => 'top',
                ),
                array(
                    'key'           => 'field_short_about_title',
                    'label'         => 'Title',
                    'name'          => 'short_about_title',
                    'type'          => 'text',
                    'instructions'  => 'Heading for the Short Product About section.',
                ),
                array(
                    'key'           => 'field_short_about_description',
                    'label'         => 'Description',
                    'name'          => 'short_about_description',
                    'type'          => 'wysiwyg',
                    'instructions'  => 'Enter the short product description.',
                    'tabs'          => 'all',
                    'toolbar'       => 'full',
                    'media_upload'  => true,
                ),
                array(
                    'key'           => 'field_short_about_image',
                    'label'         => 'Image',
                    'name'          => 'short_about_image',
                    'type'          => 'image',
                    'instructions'  => 'Upload an image for the Short Product About section.',
                    'return_format' => 'url',
                ),
                // Video Testimonials tab
                array(
                    'key'   => 'tab_video_testimonials',
                    'label' => 'Video Testimonials',
                    'type'  => 'tab',
                    'placement' => 'top',
                ),
                array(
                    'key' => 'field_video_testimonial_1_file',
                    'label' => 'Video Testimonial 1',
                    'name' => 'video_testimonial_1_file',
                    'type' => 'file',
                    'instructions' => 'Upload the MP4 file for the first video testimonial (vertical mobile, TikTok format).',
                    'return_format' => 'url',
                    'mime_types' => 'mp4',
                ),
                array(
                    'key' => 'field_video_testimonial_1_description',
                    'label' => 'Video Testimonial 1 Description',
                    'name' => 'video_testimonial_1_description',
                    'type' => 'textarea',
                    'instructions' => 'Enter a short description for the first video testimonial.',
                ),
                array(
                    'key' => 'field_video_testimonial_2_file',
                    'label' => 'Video Testimonial 2',
                    'name' => 'video_testimonial_2_file',
                    'type' => 'file',
                    'instructions' => 'Upload the MP4 file for the second video testimonial (vertical mobile, TikTok format).',
                    'return_format' => 'url',
                    'mime_types' => 'mp4',
                ),
                array(
                    'key' => 'field_video_testimonial_2_description',
                    'label' => 'Video Testimonial 2 Description',
                    'name' => 'video_testimonial_2_description',
                    'type' => 'textarea',
                    'instructions' => 'Enter a short description for the second video testimonial.',
                ),
                array(
                    'key' => 'field_video_testimonial_3_file',
                    'label' => 'Video Testimonial 3',
                    'name' => 'video_testimonial_3_file',
                    'type' => 'file',
                    'instructions' => 'Upload the MP4 file for the third video testimonial (vertical mobile, TikTok format).',
                    'return_format' => 'url',
                    'mime_types' => 'mp4',
                ),
                array(
                    'key' => 'field_video_testimonial_3_description',
                    'label' => 'Video Testimonial 3 Description',
                    'name' => 'video_testimonial_3_description',
                    'type' => 'textarea',
                    'instructions' => 'Enter a short description for the third video testimonial.',
                ),
                // Insert Facts & Use tab and fields
                array(
                    'key'   => 'tab_facts_use',
                    'label' => 'Facts & Use',
                    'type'  => 'tab',
                    'placement' => 'top',
                ),
                array(
                    'key'           => 'field_facts_use_title',
                    'label'         => 'Title',
                    'name'          => 'facts_use_title',
                    'type'          => 'text',
                    'default_value' => 'Facts & Use',
                ),
                array(
                    'key'           => 'field_facts_use_content',
                    'label'         => 'Content',
                    'name'          => 'facts_use_content',
                    'type'          => 'wysiwyg',
                    'instructions'  => 'Enter facts and usage information.',
                    'tabs'          => 'all',
                    'toolbar'       => 'full',
                    'media_upload'  => true,
                ),
                array(
                    'key'           => 'field_facts_use_image',
                    'label'         => 'Supplement Facts Image',
                    'name'          => 'facts_use_image',
                    'type'          => 'image',
                    'instructions'  => 'Upload a supplement facts image or any other relevant image.',
                    'return_format' => 'url',
                ),
                // New fields: Facts List (text)
                array(
                    'key'           => 'field_facts_list_1',
                    'label'         => 'Fact 1',
                    'name'          => 'facts_list_1',
                    'type'          => 'text',
                    'instructions'  => 'Enter the first fact (inline list).',
                ),
                array(
                    'key'           => 'field_facts_list_2',
                    'label'         => 'Fact 2',
                    'name'          => 'facts_list_2',
                    'type'          => 'text',
                    'instructions'  => 'Enter the second fact (inline list).',
                ),
                array(
                    'key'           => 'field_facts_list_3',
                    'label'         => 'Fact 3',
                    'name'          => 'facts_list_3',
                    'type'          => 'text',
                    'instructions'  => 'Enter the third fact (inline list).',
                ),
                // New fields: Label Images (e.g., FDA Approved)
                array(
                    'key'           => 'field_facts_label_image_1',
                    'label'         => 'Label Image 1',
                    'name'          => 'facts_label_image_1',
                    'type'          => 'image',
                    'instructions'  => 'Upload a label image (e.g., FDA Approved).',
                    'return_format' => 'url',
                ),
                array(
                    'key'           => 'field_facts_label_image_2',
                    'label'         => 'Label Image 2',
                    'name'          => 'facts_label_image_2',
                    'type'          => 'image',
                    'instructions'  => 'Upload a second label image.',
                    'return_format' => 'url',
                ),
                array(
                    'key'           => 'field_facts_label_image_3',
                    'label'         => 'Label Image 3',
                    'name'          => 'facts_label_image_3',
                    'type'          => 'image',
                    'instructions'  => 'Upload a third label image.',
                    'return_format' => 'url',
                ),
                array(
                    'key'           => 'field_facts_use_reference_1',
                    'label'         => 'Reference 1',
                    'name'          => 'facts_use_reference_1',
                    'type'          => 'text',
                    'instructions'  => 'Enter a reference source.',
                ),
                array(
                    'key'           => 'field_facts_use_reference_2',
                    'label'         => 'Reference 2',
                    'name'          => 'facts_use_reference_2',
                    'type'          => 'text',
                    'instructions'  => 'Enter a second reference source (optional).',
                ),
                array(
                    'key'           => 'field_facts_use_reference_3',
                    'label'         => 'Reference 3',
                    'name'          => 'facts_use_reference_3',
                    'type'          => 'text',
                    'instructions'  => 'Enter a third reference source (optional).',
                ),
                // Add What Do Experts Say tab and fields
                array(
                    'key'   => 'tab_experts_says',
                    'label' => 'What Do Experts Say',
                    'type'  => 'tab',
                    'placement' => 'top',
                ),
                array(
                    'key'   => 'field_experts_title',
                    'label' => 'Title H2',
                    'name'  => 'experts_title',
                    'type'  => 'text',
                    'instructions' => 'Enter the section title for What Do Experts Say.',
                ),
                // Expert 1 fields
                array(
                    'key'   => 'field_expert_1_video',
                    'label' => 'Expert 1 Video',
                    'name'  => 'expert_1_video',
                    'type'  => 'file',
                    'instructions' => 'Upload the MP4 video of the first expert.',
                    'return_format' => 'url',
                    'mime_types' => 'mp4',
                ),
                array(
                    'key'   => 'field_expert_1_image',
                    'label' => 'Expert 1 Image',
                    'name'  => 'expert_1_image',
                    'type'  => 'image',
                    'instructions' => 'Upload the image of the first expert.',
                    'return_format' => 'url',
                ),
                array(
                    'key'   => 'field_expert_1_name',
                    'label' => 'Expert 1 Name',
                    'name'  => 'expert_1_name',
                    'type'  => 'text',
                    'instructions' => 'Enter the name of the first expert.',
                ),
                array(
                    'key'   => 'field_expert_1_title',
                    'label' => 'Expert 1 Title',
                    'name'  => 'expert_1_title',
                    'type'  => 'text',
                    'instructions' => 'Enter the title of the first expert.',
                ),
                array(
                    'key'   => 'field_expert_1_text',
                    'label' => 'Expert 1 Text',
                    'name'  => 'expert_1_text',
                    'type'  => 'textarea',
                    'instructions' => 'Enter the review text of the first expert.',
                ),
                // Expert 2 fields
                array(
                    'key'   => 'field_expert_2_video',
                    'label' => 'Expert 2 Video',
                    'name'  => 'expert_2_video',
                    'type'  => 'file',
                    'instructions' => 'Upload the MP4 video of the second expert.',
                    'return_format' => 'url',
                    'mime_types' => 'mp4',
                ),
                array(
                    'key'   => 'field_expert_2_image',
                    'label' => 'Expert 2 Image',
                    'name'  => 'expert_2_image',
                    'type'  => 'image',
                    'instructions' => 'Upload the image of the second expert.',
                    'return_format' => 'url',
                ),
                array(
                    'key'   => 'field_expert_2_name',
                    'label' => 'Expert 2 Name',
                    'name'  => 'expert_2_name',
                    'type'  => 'text',
                    'instructions' => 'Enter the name of the second expert.',
                ),
                array(
                    'key'   => 'field_expert_2_title',
                    'label' => 'Expert 2 Title',
                    'name'  => 'expert_2_title',
                    'type'  => 'text',
                    'instructions' => 'Enter the title of the second expert.',
                ),
                array(
                    'key'   => 'field_expert_2_text',
                    'label' => 'Expert 2 Text',
                    'name'  => 'expert_2_text',
                    'type'  => 'textarea',
                    'instructions' => 'Enter the review text of the second expert.',
                ),
                // Expert 3 fields
                array(
                    'key'   => 'field_expert_3_video',
                    'label' => 'Expert 3 Video',
                    'name'  => 'expert_3_video',
                    'type'  => 'file',
                    'instructions' => 'Upload the MP4 video of the third expert.',
                    'return_format' => 'url',
                    'mime_types' => 'mp4',
                ),
                array(
                    'key'   => 'field_expert_3_image',
                    'label' => 'Expert 3 Image',
                    'name'  => 'expert_3_image',
                    'type'  => 'image',
                    'instructions' => 'Upload the image of the third expert.',
                    'return_format' => 'url',
                ),
                array(
                    'key'   => 'field_expert_3_name',
                    'label' => 'Expert 3 Name',
                    'name'  => 'expert_3_name',
                    'type'  => 'text',
                    'instructions' => 'Enter the name of the third expert.',
                ),
                array(
                    'key'   => 'field_expert_3_title',
                    'label' => 'Expert 3 Title',
                    'name'  => 'expert_3_title',
                    'type'  => 'text',
                    'instructions' => 'Enter the title of the third expert.',
                ),
                array(
                    'key'   => 'field_expert_3_text',
                    'label' => 'Expert 3 Text',
                    'name'  => 'expert_3_text',
                    'type'  => 'textarea',
                    'instructions' => 'Enter the review text of the third expert.',
                ),
                // Add More About Product tab and fields
                array(
                    'key'   => 'tab_more_about_product',
                    'label' => 'More About Product',
                    'type'  => 'tab',
                    'placement' => 'top',
                ),
                // Section 1: text left, images right
                array(
                    'key'   => 'field_more_about_title_1',
                    'label' => 'More About Title 1',
                    'name'  => 'more_about_title_1',
                    'type'  => 'text',
                    'instructions' => 'Enter the H2 title for the More About Product section.',
                ),
                array(
                    'key'   => 'field_more_about_content_1',
                    'label' => 'More About Content 1',
                    'name'  => 'more_about_content_1',
                    'type'  => 'wysiwyg',
                    'instructions' => 'Enter the content for the More About Product section.',
                    'tabs'  => 'all',
                    'toolbar'=> 'full',
                    'media_upload' => true,
                ),
                array(
                    'key'   => 'field_more_about_image_top_1',
                    'label' => 'More About Top Image 1',
                    'name'  => 'more_about_image_top_1',
                    'type'  => 'image',
                    'instructions' => 'Upload the top image for More About Product section.',
                    'return_format' => 'url',
                ),
                array(
                    'key'   => 'field_more_about_image_bottom_1',
                    'label' => 'More About Bottom Image 1',
                    'name'  => 'more_about_image_bottom_1',
                    'type'  => 'image',
                    'instructions' => 'Upload the bottom image for More About Product section.',
                    'return_format' => 'url',
                ),
                // Section 2: reversed layout
                array(
                    'key'   => 'field_more_about_title_2',
                    'label' => 'More About Title 2',
                    'name'  => 'more_about_title_2',
                    'type'  => 'text',
                    'instructions' => 'Enter the H2 title for the second More About Product section.',
                ),
                array(
                    'key'   => 'field_more_about_content_2',
                    'label' => 'More About Content 2',
                    'name'  => 'more_about_content_2',
                    'type'  => 'wysiwyg',
                    'instructions' => 'Enter the content for the second More About Product section.',
                    'tabs'  => 'all',
                    'toolbar'=> 'full',
                    'media_upload' => true,
                ),
                array(
                    'key'   => 'field_more_about_image_top_2',
                    'label' => 'More About Top Image 2',
                    'name'  => 'more_about_image_top_2',
                    'type'  => 'image',
                    'instructions' => 'Upload the top image for the second More About Product section.',
                    'return_format' => 'url',
                ),
                array(
                    'key'   => 'field_more_about_image_bottom_2',
                    'label' => 'More About Bottom Image 2',
                    'name'  => 'more_about_image_bottom_2',
                    'type'  => 'image',
                    'instructions' => 'Upload the bottom image for the second More About Product section.',
                    'return_format' => 'url',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'page_template',
                        'operator' => '==',
                        'value' => 'one-pager-template.php',
                    ),
                ),
            ),
        ));
    }
}
add_action('acf/init', 'opalp_register_custom_fields');