<?php
// Register custom fields programmatically for the One-Pager Affiliate Landing Page Plugin

function opalp_register_custom_fields() {
    if (function_exists('acf_add_local_field_group')) {
        // Dynamically build choices for payment images checkbox
        $payment_images_dir = plugin_dir_path(__FILE__) . '../assets/payments-images/';
        $payment_images_choices = array();
        if (is_dir($payment_images_dir)) {
            foreach (scandir($payment_images_dir) as $file) {
                if (is_file($payment_images_dir . $file) && preg_match('/\.(png|jpe?g|gif)$/i', $file)) {
                    $payment_images_choices[$file] = $file;
                }
            }
        }

        acf_add_local_field_group(array(
            'key' => 'group_one_pager_fields',
            'title' => 'One-Pager Fields',
            'fields' => array(
                // Tab for Top Header settings
                array(
                    'key'   => 'tab_top_header',
                    'label' => 'Top Header',
                    'type'  => 'tab',
                    'placement' => 'top',
                ),
                // Group for Header Bar Content
                array(
                    'key' => 'group_header_bar_content',
                    'label' => 'Header Bar Content',
                    'name' => 'header_bar_content',
                    'type' => 'group',
                    'instructions' => 'Settings for the top notification bar.',
                    'layout' => 'block', // Or 'table' or 'row'
                    'sub_fields' => array(
                        array(
                            'key' => 'field_top_header_text_string',
                            'label' => 'Top Header Text String',
                            'name' => 'top_header_text_string',
                            'type' => 'text',
                            'instructions' => 'Enter the text to display in the top header bar (optional).',
                            'wrapper' => array(
                                'width' => '50',
                            ),
                        ),
                        array(
                            'key' => 'field_countdown_date',
                            'label' => 'Countdown End Date',
                            'name' => 'countdown_date',
                            'type' => 'date_picker',
                            'instructions' => 'Select the date the countdown should end (optional).',
                            'display_format' => 'Y-m-d',
                            'return_format' => 'Y-m-d',
                            'wrapper' => array(
                                'width' => '25',
                            ),
                        ),
                        array(
                            'key' => 'field_show_visitor_count_top_header',
                            'label' => 'Show Visitor Count',
                            'name' => 'show_visitor_count_in_top_header',
                            'type' => 'true_false',
                            'instructions' => 'Display live visitor count in the top bar?',
                            'ui' => 1,
                            'wrapper' => array(
                                'width' => '25',
                            ),
                        ),
                    )
                ),
                array(
                    'key' => 'field_header_logo',
                    'label' => 'Header Logo',
                    'name' => 'header_logo',
                    'type' => 'image',
                    'instructions' => 'Upload the logo for the header.',
                    'return_format' => 'url',
                ),
                // Tab for Hero Section
                array(
                    'key'   => 'tab_hero_section',
                    'label' => 'Hero Section',
                    'type'  => 'tab',
                    'placement' => 'top',
                ),
                // Hero Section Fields (left column)
                array(
                    'key' => 'field_hero_video_file',
                    'label' => 'Hero Video File',
                    'name' => 'hero_video_file',
                    'type' => 'file',
                    'instructions' => 'Upload the MP4 file for the hero video.',
                    'return_format' => 'url',
                    'mime_types' => 'mp4',
                ),
                array(
                    'key' => 'field_hero_video_thumbnail',
                    'label' => 'Hero Video Thumbnail',
                    'name' => 'hero_video_thumbnail',
                    'type' => 'image',
                    'instructions' => 'Upload a thumbnail image that will be shown before the video plays.',
                    'return_format' => 'url',
                ),
                array(
                    'key' => 'field_hero_video_url',
                    'label' => 'Hero Video URL',
                    'name' => 'hero_video_url',
                    'type' => 'url',
                    'instructions' => 'Enter the YouTube URL for the hero video.',
                ),
                array(
                    'key' => 'field_fallback_hero_image',
                    'label' => 'Fallback Hero Image',
                    'name' => 'fallback_hero_image',
                    'type' => 'image',
                    'instructions' => 'Upload an image to display if no hero video is provided.',
                    'return_format' => 'url',
                ),
                array(
                    'key' => 'field_video_description',
                    'label' => 'Video Description',
                    'name' => 'video_description',
                    'type' => 'textarea',
                    'instructions' => 'Enter a description for the video.',
                ),
                // Hero Section Fields (right column)
                array(
                    'key' => 'field_product_name',
                    'label' => 'Product Name',
                    'name' => 'product_name',
                    'type' => 'text',
                    'instructions' => 'Enter the product name.',
                ),
                array(
                    'key' => 'field_product_rating',
                    'label' => 'Product Rating',
                    'name' => 'product_rating',
                    'type' => 'number',
                    'instructions' => 'Set the product rating (1 to 5, with up to one decimal place).',
                    'min' => 1,
                    'max' => 5,
                    'step' => 0.1,
                ),
                array(
                    'key' => 'field_number_of_reviews',
                    'label' => 'Number of Reviews',
                    'name' => 'number_of_reviews',
                    'type' => 'number',
                    'instructions' => 'Enter the number of reviews for the product.',
                    'min' => 0,
                    'step' => 1,
                ),
                array(
                    'key' => 'field_headline',
                    'label' => 'Headline',
                    'name' => 'headline',
                    'type' => 'text',
                    'instructions' => 'Enter the headline.',
                ),
                array(
                    'key' => 'field_subheadline',
                    'label' => 'Subheadline',
                    'name' => 'subheadline',
                    'type' => 'text',
                    'instructions' => 'Enter the subheadline.',
                ),
                array(
                    'key' => 'field_can_from_apply_to_price',
                    'label' => 'Add "From" Before Price',
                    'name' => 'can_from_apply_to_price',
                    'type' => 'true_false',
                    'instructions' => 'Add "From" text before the price display.',
                    'ui' => 1,
                    'ui_on_text' => 'Yes',
                    'ui_off_text' => 'No',
                    'default_value' => 0,
                ),
                array(
                    'key' => 'field_price',
                    'label' => 'Price',
                    'name' => 'price',
                    'type' => 'number',
                    'instructions' => 'Enter the product price.',
                    'min' => 0,
                    'step' => 0.01,
                    'wrapper' => array(
                        'width' => '33',
                    ),
                ),
                array(
                    'key' => 'field_discount_price',
                    'label' => 'Discount Price',
                    'name' => 'discount_price',
                    'type' => 'number',
                    'instructions' => 'Enter the discount price (if applicable).',
                    'min' => 0,
                    'step' => 0.01,
                    'wrapper' => array(
                        'width' => '33',
                    ),
                ),
                array(
                    'key' => 'field_cost_per_day',
                    'label' => 'Cost Per Day',
                    'name' => 'cost_per_day',
                    'type' => 'text',
                    'instructions' => 'Enter the cost per day/use (e.g. "$0.30 for brushing" or "$0.54 per day").',
                    'wrapper' => array(
                        'width' => '33',
                    ),
                ),
                array(
                    'key' => 'field_bonus_offer_text',
                    'label' => 'Bonus Offer Text',
                    'name' => 'bonus_offer_text',
                    'type' => 'text',
                    'instructions' => 'Enter the bonus offer text to display alongside the price (optional).',
                    'wrapper' => array(
                        'width' => '33',
                    ),
                ),
                array(
                    'key' => 'field_button_1_text',
                    'label' => 'Button 1 Text',
                    'name' => 'button_1_text',
                    'type' => 'text',
                    'instructions' => 'Enter the text for the first call-to-action button.',
                ),
                array(
                    'key' => 'field_button_1_url',
                    'label' => 'Button 1 URL',
                    'name' => 'button_1_url',
                    'type' => 'url',
                    'instructions' => 'Enter the URL for the first call-to-action button.',
                ),
                array(
                    'key' => 'field_payment_images',
                    'label' => 'Payment Images',
                    'name' => 'payment_images',
                    'type' => 'checkbox',
                    'instructions' => 'Select payment images to display.',
                    'choices' => $payment_images_choices,
                    'layout' => 'horizontal',
                ),
                array(
                    'key' => 'field_money_back_days',
                    'label' => 'Days for Money Back Guarantee',
                    'name' => 'money_back_days',
                    'type' => 'number',
                    'instructions' => 'Enter the number of days for the money-back guarantee.',
                    'min' => 0,
                ),
                
                // Add Featured On / Approved By tab and fields (previously "As Seen On")
                array(
                    'key'   => 'tab_as_seen_on',
                    'label' => 'Featured On / Approved By',
                    'type'  => 'tab',
                    'placement' => 'top',
                ),
                array(
                    'key'           => 'field_as_seen_on_title',
                    'label'         => 'H2 Title',
                    'name'          => 'as_seen_on_title',
                    'type'          => 'text',
                    'instructions'  => 'Heading for the Featured On / Approved By section.',
                    'default_value' => 'Featured On / Approved By',
                ),
                array(
                    'key'           => 'field_as_seen_on_image_1',
                    'label'         => 'Image 1',
                    'name'          => 'as_seen_on_image_1',
                    'type'          => 'image',
                    'instructions'  => 'Upload the first logo.',
                    'return_format' => 'url',
                ),
                array(
                    'key'           => 'field_as_seen_on_image_2',
                    'label'         => 'Image 2',
                    'name'          => 'as_seen_on_image_2',
                    'type'          => 'image',
                    'instructions'  => 'Upload the second logo.',
                    'return_format' => 'url',
                ),
                array(
                    'key'           => 'field_as_seen_on_image_3',
                    'label'         => 'Image 3',
                    'name'          => 'as_seen_on_image_3',
                    'type'          => 'image',
                    'instructions'  => 'Upload the third logo.',
                    'return_format' => 'url',
                ),
                array(
                    'key'           => 'field_as_seen_on_image_4',
                    'label'         => 'Image 4',
                    'name'          => 'as_seen_on_image_4',
                    'type'          => 'image',
                    'instructions'  => 'Upload the fourth logo.',
                    'return_format' => 'url',
                ),
                array(
                    'key'           => 'field_as_seen_on_image_5',
                    'label'         => 'Image 5',
                    'name'          => 'as_seen_on_image_5',
                    'type'          => 'image',
                    'instructions'  => 'Upload the fifth logo.',
                    'return_format' => 'url',
                ),
                array(
                    'key'           => 'field_as_seen_on_image_6',
                    'label'         => 'Image 6',
                    'name'          => 'as_seen_on_image_6',
                    'type'          => 'image',
                    'instructions'  => 'Upload the sixth logo.',
                    'return_format' => 'url',
                ),
                array(
                    'key'   => 'tab_short_product_about',
                    'label' => 'Short Product About',
                    'type'  => 'tab',
                    'placement' => 'top',
                ),
                array(
                    'key'           => 'field_short_about_title',
                    'label'         => 'Title',
                    'name'          => 'short_about_title',
                    'type'          => 'text',
                    'instructions'  => 'Heading for the Short Product About section.',
                ),
                array(
                    'key'           => 'field_short_about_description',
                    'label'         => 'Description',
                    'name'          => 'short_about_description',
                    'type'          => 'wysiwyg',
                    'instructions'  => 'Enter the short product description.',
                    'tabs'          => 'all',
                    'toolbar'       => 'full',
                    'media_upload'  => true,
                ),
                array(
                    'key'           => 'field_blurb_item_1',
                    'label'         => 'Blurb Item 1',
                    'name'          => 'short_about_blurb_1',
                    'type'          => 'text',
                    'instructions'  => 'Enter the first blurb item text',
                ),
                array(
                    'key'           => 'field_blurb_item_2',
                    'label'         => 'Blurb Item 2',
                    'name'          => 'short_about_blurb_2',
                    'type'          => 'text',
                    'instructions'  => 'Enter the second blurb item text',
                ),
                array(
                    'key'           => 'field_blurb_item_3',
                    'label'         => 'Blurb Item 3',
                    'name'          => 'short_about_blurb_3',
                    'type'          => 'text',
                    'instructions'  => 'Enter the third blurb item text',
                ),
                array(
                    'key'           => 'field_short_about_image',
                    'label'         => 'Image',
                    'name'          => 'short_about_image',
                    'type'          => 'image',
                    'instructions'  => 'Upload an image for the Short Product About section.',
                    'return_format' => 'url',
                ),
                // Video Testimonials tab
                array(
                    'key'   => 'tab_video_testimonials',
                    'label' => 'Video Testimonials',
                    'type'  => 'tab',
                    'placement' => 'top',
                ),
                array(
                    'key' => 'field_video_testimonials_title',
                    'label' => 'Video Testimonials Title',
                    'name' => 'video_testimonials_title',
                    'type' => 'text',
                    'instructions' => 'Enter the heading for the Video Testimonials section (displayed as H2)',
                    'default_value' => 'Testimonials',
                ),
                array(
                    'key' => 'field_video_testimonial_1_file',
                    'label' => 'Video Testimonial 1',
                    'name' => 'video_testimonial_1_file',
                    'type' => 'file',
                    'instructions' => 'Upload the MP4 file for the first video testimonial (vertical mobile, TikTok format).',
                    'return_format' => 'url',
                    'mime_types' => 'mp4',
                ),
                array(
                    'key' => 'field_video_testimonial_1_thumbnail',
                    'label' => 'Video Testimonial 1 Thumbnail',
                    'name' => 'video_testimonial_1_thumbnail',
                    'type' => 'image',
                    'instructions' => 'Upload a thumbnail image for the first video testimonial.',
                    'return_format' => 'url',
                ),
                array(
                    'key' => 'field_video_testimonial_1_description',
                    'label' => 'Video Testimonial 1 Description',
                    'name' => 'video_testimonial_1_description',
                    'type' => 'textarea',
                    'instructions' => 'Enter a short description for the first video testimonial.',
                ),
                array(
                    'key' => 'field_video_testimonial_1_name',
                    'label' => 'Video Testimonial 1 Reviewer Name',
                    'name' => 'video_testimonial_1_name',
                    'type' => 'text',
                    'instructions' => 'Enter the name of the reviewer for the first video testimonial.',
                ),
                array(
                    'key' => 'field_video_testimonial_2_file',
                    'label' => 'Video Testimonial 2',
                    'name' => 'video_testimonial_2_file',
                    'type' => 'file',
                    'instructions' => 'Upload the MP4 file for the second video testimonial (vertical mobile, TikTok format).',
                    'return_format' => 'url',
                    'mime_types' => 'mp4',
                ),
                array(
                    'key' => 'field_video_testimonial_2_thumbnail',
                    'label' => 'Video Testimonial 2 Thumbnail',
                    'name' => 'video_testimonial_2_thumbnail',
                    'type' => 'image',
                    'instructions' => 'Upload a thumbnail image for the second video testimonial.',
                    'return_format' => 'url',
                ),
                array(
                    'key' => 'field_video_testimonial_2_description',
                    'label' => 'Video Testimonial 2 Description',
                    'name' => 'video_testimonial_2_description',
                    'type' => 'textarea',
                    'instructions' => 'Enter a short description for the second video testimonial.',
                ),
                array(
                    'key' => 'field_video_testimonial_2_name',
                    'label' => 'Video Testimonial 2 Reviewer Name',
                    'name' => 'video_testimonial_2_name',
                    'type' => 'text',
                    'instructions' => 'Enter the name of the reviewer for the second video testimonial.',
                ),
                array(
                    'key' => 'field_video_testimonial_3_file',
                    'label' => 'Video Testimonial 3',
                    'name' => 'video_testimonial_3_file',
                    'type' => 'file',
                    'instructions' => 'Upload the MP4 file for the third video testimonial (vertical mobile, TikTok format).',
                    'return_format' => 'url',
                    'mime_types' => 'mp4',
                ),
                array(
                    'key' => 'field_video_testimonial_3_thumbnail',
                    'label' => 'Video Testimonial 3 Thumbnail',
                    'name' => 'video_testimonial_3_thumbnail',
                    'type' => 'image',
                    'instructions' => 'Upload a thumbnail image for the third video testimonial.',
                    'return_format' => 'url',
                ),
                array(
                    'key' => 'field_video_testimonial_3_description',
                    'label' => 'Video Testimonial 3 Description',
                    'name' => 'video_testimonial_3_description',
                    'type' => 'textarea',
                    'instructions' => 'Enter a short description for the third video testimonial.',
                ),
                array(
                    'key' => 'field_video_testimonial_3_name',
                    'label' => 'Video Testimonial 3 Reviewer Name',
                    'name' => 'video_testimonial_3_name',
                    'type' => 'text',
                    'instructions' => 'Enter the name of the reviewer for the third video testimonial.',
                ),
                // Additional Video Testimonial 4
                array(
                    'key' => 'field_video_testimonial_4_file',
                    'label' => 'Video Testimonial 4',
                    'name' => 'video_testimonial_4_file',
                    'type' => 'file',
                    'instructions' => 'Upload the MP4 file for the fourth video testimonial (vertical mobile, TikTok format).',
                    'return_format' => 'url',
                    'mime_types' => 'mp4',
                ),
                array(
                    'key' => 'field_video_testimonial_4_thumbnail',
                    'label' => 'Video Testimonial 4 Thumbnail',
                    'name' => 'video_testimonial_4_thumbnail',
                    'type' => 'image',
                    'instructions' => 'Upload a thumbnail image for the fourth video testimonial.',
                    'return_format' => 'url',
                ),
                array(
                    'key' => 'field_video_testimonial_4_description',
                    'label' => 'Video Testimonial 4 Description',
                    'name' => 'video_testimonial_4_description',
                    'type' => 'textarea',
                    'instructions' => 'Enter a short description for the fourth video testimonial.',
                ),
                array(
                    'key' => 'field_video_testimonial_4_name',
                    'label' => 'Video Testimonial 4 Reviewer Name',
                    'name' => 'video_testimonial_4_name',
                    'type' => 'text',
                    'instructions' => 'Enter the name of the reviewer for the fourth video testimonial.',
                ),
                // Additional Video Testimonial 5
                array(
                    'key' => 'field_video_testimonial_5_file',
                    'label' => 'Video Testimonial 5',
                    'name' => 'video_testimonial_5_file',
                    'type' => 'file',
                    'instructions' => 'Upload the MP4 file for the fifth video testimonial (vertical mobile, TikTok format).',
                    'return_format' => 'url',
                    'mime_types' => 'mp4',
                ),
                array(
                    'key' => 'field_video_testimonial_5_thumbnail',
                    'label' => 'Video Testimonial 5 Thumbnail',
                    'name' => 'video_testimonial_5_thumbnail',
                    'type' => 'image',
                    'instructions' => 'Upload a thumbnail image for the fifth video testimonial.',
                    'return_format' => 'url',
                ),
                array(
                    'key' => 'field_video_testimonial_5_description',
                    'label' => 'Video Testimonial 5 Description',
                    'name' => 'video_testimonial_5_description',
                    'type' => 'textarea',
                    'instructions' => 'Enter a short description for the fifth video testimonial.',
                ),
                array(
                    'key' => 'field_video_testimonial_5_name',
                    'label' => 'Video Testimonial 5 Reviewer Name',
                    'name' => 'video_testimonial_5_name',
                    'type' => 'text',
                    'instructions' => 'Enter the name of the reviewer for the fifth video testimonial.',
                ),
                // Additional Video Testimonial 6
                array(
                    'key' => 'field_video_testimonial_6_file',
                    'label' => 'Video Testimonial 6',
                    'name' => 'video_testimonial_6_file',
                    'type' => 'file',
                    'instructions' => 'Upload the MP4 file for the sixth video testimonial (vertical mobile, TikTok format).',
                    'return_format' => 'url',
                    'mime_types' => 'mp4',
                ),
                array(
                    'key' => 'field_video_testimonial_6_thumbnail',
                    'label' => 'Video Testimonial 6 Thumbnail',
                    'name' => 'video_testimonial_6_thumbnail',
                    'type' => 'image',
                    'instructions' => 'Upload a thumbnail image for the sixth video testimonial.',
                    'return_format' => 'url',
                ),
                array(
                    'key' => 'field_video_testimonial_6_description',
                    'label' => 'Video Testimonial 6 Description',
                    'name' => 'video_testimonial_6_description',
                    'type' => 'textarea',
                    'instructions' => 'Enter a short description for the sixth video testimonial.',
                ),
                array(
                    'key' => 'field_video_testimonial_6_name',
                    'label' => 'Video Testimonial 6 Reviewer Name',
                    'name' => 'video_testimonial_6_name',
                    'type' => 'text',
                    'instructions' => 'Enter the name of the reviewer for the sixth video testimonial.',
                ),
                // Insert Facts & Use tab and fields
                array(
                    'key'   => 'tab_facts_use',
                    'label' => 'Facts & Use',
                    'type'  => 'tab',
                    'placement' => 'top',
                ),
                array(
                    'key'           => 'field_facts_use_title',
                    'label'         => 'Title',
                    'name'          => 'facts_use_title',
                    'type'          => 'text',
                    'default_value' => 'Facts & Use',
                ),
                array(
                    'key'           => 'field_facts_use_content',
                    'label'         => 'Content',
                    'name'          => 'facts_use_content',
                    'type'          => 'wysiwyg',
                    'instructions'  => 'Enter facts and usage information.',
                    'tabs'          => 'all',
                    'toolbar'       => 'full',
                    'media_upload'  => true,
                ),
                array(
                    'key'           => 'field_facts_use_image',
                    'label'         => 'Supplement Facts Image',
                    'name'          => 'facts_use_image',
                    'type'          => 'image',
                    'instructions'  => 'Upload a supplement facts image or any other relevant image.',
                    'return_format' => 'url',
                ),
                // New fields: Facts List (text)
                array(
                    'key'           => 'field_facts_list_1',
                    'label'         => 'Fact 1',
                    'name'          => 'facts_list_1',
                    'type'          => 'text',
                    'instructions'  => 'Enter the first fact (inline list).',
                ),
                array(
                    'key'           => 'field_facts_list_2',
                    'label'         => 'Fact 2',
                    'name'          => 'facts_list_2',
                    'type'          => 'text',
                    'instructions'  => 'Enter the second fact (inline list).',
                ),
                array(
                    'key'           => 'field_facts_list_3',
                    'label'         => 'Fact 3',
                    'name'          => 'facts_list_3',
                    'type'          => 'text',
                    'instructions'  => 'Enter the third fact (inline list).',
                ),
                // New fields: Label Images (e.g., FDA Approved)
                array(
                    'key'           => 'field_facts_label_image_1',
                    'label'         => 'Label Image 1',
                    'name'          => 'facts_label_image_1',
                    'type'          => 'image',
                    'instructions'  => 'Upload a label image (e.g., FDA Approved).',
                    'return_format' => 'url',
                ),
                array(
                    'key'           => 'field_facts_label_image_2',
                    'label'         => 'Label Image 2',
                    'name'          => 'facts_label_image_2',
                    'type'          => 'image',
                    'instructions'  => 'Upload a second label image.',
                    'return_format' => 'url',
                ),
                array(
                    'key'           => 'field_facts_label_image_3',
                    'label'         => 'Label Image 3',
                    'name'          => 'facts_label_image_3',
                    'type'          => 'image',
                    'instructions'  => 'Upload a third label image.',
                    'return_format' => 'url',
                ),
                array(
                    'key'           => 'field_facts_use_reference_1',
                    'label'         => 'Reference 1',
                    'name'          => 'facts_use_reference_1',
                    'type'          => 'text',
                    'instructions'  => 'Enter a reference source.',
                ),
                array(
                    'key'           => 'field_facts_use_reference_2',
                    'label'         => 'Reference 2',
                    'name'          => 'facts_use_reference_2',
                    'type'          => 'text',
                    'instructions'  => 'Enter a second reference source (optional).',
                ),
                array(
                    'key'           => 'field_facts_use_reference_3',
                    'label'         => 'Reference 3',
                    'name'          => 'facts_use_reference_3',
                    'type'          => 'text',
                    'instructions'  => 'Enter a third reference source (optional).',
                ),
                // Add What Do Experts Say tab and fields
                array(
                    'key'   => 'tab_experts_says',
                    'label' => 'What Do Experts Say',
                    'type'  => 'tab',
                    'placement' => 'top',
                ),
                array(
                    'key'   => 'field_experts_title',
                    'label' => 'Title H2',
                    'name'  => 'experts_title',
                    'type'  => 'text',
                    'instructions' => 'Enter the section title for What Do Experts Say.',
                ),
                // Expert 1 fields
                array(
                    'key'   => 'field_expert_1_video',
                    'label' => 'Expert 1 Video',
                    'name'  => 'expert_1_video',
                    'type'  => 'file',
                    'instructions' => 'Upload the MP4 video of the first expert.',
                    'return_format' => 'url',
                    'mime_types' => 'mp4',
                ),
                array(
                    'key'   => 'field_expert_1_image',
                    'label' => 'Expert 1 Image',
                    'name'  => 'expert_1_image',
                    'type'  => 'image',
                    'instructions' => 'Upload the image of the first expert.',
                    'return_format' => 'url',
                ),
                array(
                    'key'   => 'field_expert_1_name',
                    'label' => 'Expert 1 Name',
                    'name'  => 'expert_1_name',
                    'type'  => 'text',
                    'instructions' => 'Enter the name of the first expert.',
                ),
                array(
                    'key'   => 'field_expert_1_title',
                    'label' => 'Expert 1 Title',
                    'name'  => 'expert_1_title',
                    'type'  => 'text',
                    'instructions' => 'Enter the title of the first expert.',
                ),
                array(
                    'key'   => 'field_expert_1_text',
                    'label' => 'Expert 1 Text',
                    'name'  => 'expert_1_text',
                    'type'  => 'textarea',
                    'instructions' => 'Enter the review text of the first expert.',
                ),
                // Expert 2 fields
                array(
                    'key'   => 'field_expert_2_video',
                    'label' => 'Expert 2 Video',
                    'name'  => 'expert_2_video',
                    'type'  => 'file',
                    'instructions' => 'Upload the MP4 video of the second expert.',
                    'return_format' => 'url',
                    'mime_types' => 'mp4',
                ),
                array(
                    'key'   => 'field_expert_2_image',
                    'label' => 'Expert 2 Image',
                    'name'  => 'expert_2_image',
                    'type'  => 'image',
                    'instructions' => 'Upload the image of the second expert.',
                    'return_format' => 'url',
                ),
                array(
                    'key'   => 'field_expert_2_name',
                    'label' => 'Expert 2 Name',
                    'name'  => 'expert_2_name',
                    'type'  => 'text',
                    'instructions' => 'Enter the name of the second expert.',
                ),
                array(
                    'key'   => 'field_expert_2_title',
                    'label' => 'Expert 2 Title',
                    'name'  => 'expert_2_title',
                    'type'  => 'text',
                    'instructions' => 'Enter the title of the second expert.',
                ),
                array(
                    'key'   => 'field_expert_2_text',
                    'label' => 'Expert 2 Text',
                    'name'  => 'expert_2_text',
                    'type'  => 'textarea',
                    'instructions' => 'Enter the review text of the second expert.',
                ),
                // Expert 3 fields
                array(
                    'key'   => 'field_expert_3_video',
                    'label' => 'Expert 3 Video',
                    'name'  => 'expert_3_video',
                    'type'  => 'file',
                    'instructions' => 'Upload the MP4 video of the third expert.',
                    'return_format' => 'url',
                    'mime_types' => 'mp4',
                ),
                array(
                    'key'   => 'field_expert_3_image',
                    'label' => 'Expert 3 Image',
                    'name'  => 'expert_3_image',
                    'type'  => 'image',
                    'instructions' => 'Upload the image of the third expert.',
                    'return_format' => 'url',
                ),
                array(
                    'key'   => 'field_expert_3_name',
                    'label' => 'Expert 3 Name',
                    'name'  => 'expert_3_name',
                    'type'  => 'text',
                    'instructions' => 'Enter the name of the third expert.',
                ),
                array(
                    'key'   => 'field_expert_3_title',
                    'label' => 'Expert 3 Title',
                    'name'  => 'expert_3_title',
                    'type'  => 'text',
                    'instructions' => 'Enter the title of the third expert.',
                ),
                array(
                    'key'   => 'field_expert_3_text',
                    'label' => 'Expert 3 Text',
                    'name'  => 'expert_3_text',
                    'type'  => 'textarea',
                    'instructions' => 'Enter the review text of the third expert.',
                ),
                // Add More About Product tab and fields
                array(
                    'key'   => 'tab_more_about_product',
                    'label' => 'More About Product',
                    'type'  => 'tab',
                    'placement' => 'top',
                ),
                // Section 1: text left, images right
                array(
                    'key'   => 'field_more_about_title_1',
                    'label' => 'More About Title 1',
                    'name'  => 'more_about_title_1',
                    'type'  => 'text',
                    'instructions' => 'Enter the H2 title for the More About Product section.',
                ),
                array(
                    'key'   => 'field_more_about_content_1',
                    'label' => 'More About Content 1',
                    'name'  => 'more_about_content_1',
                    'type'  => 'wysiwyg',
                    'instructions' => 'Enter the content for the More About Product section.',
                    'tabs'  => 'all',
                    'toolbar'=> 'full',
                    'media_upload' => true,
                ),
                array(
                    'key'   => 'field_more_about_image_top_1',
                    'label' => 'More About Top Image 1',
                    'name'  => 'more_about_image_top_1',
                    'type'  => 'image',
                    'instructions' => 'Upload the top image for More About Product section.',
                    'return_format' => 'url',
                ),
                array(
                    'key'   => 'field_more_about_image_bottom_1',
                    'label' => 'More About Bottom Image 1',
                    'name'  => 'more_about_image_bottom_1',
                    'type'  => 'image',
                    'instructions' => 'Upload the bottom image for More About Product section.',
                    'return_format' => 'url',
                ),
                // Section 2: reversed layout
                array(
                    'key'   => 'field_more_about_title_2',
                    'label' => 'More About Title 2',
                    'name'  => 'more_about_title_2',
                    'type'  => 'text',
                    'instructions' => 'Enter the H2 title for the second More About Product section.',
                ),
                array(
                    'key'   => 'field_more_about_content_2',
                    'label' => 'More About Content 2',
                    'name'  => 'more_about_content_2',
                    'type'  => 'wysiwyg',
                    'instructions' => 'Enter the content for the second More About Product section.',
                    'tabs'  => 'all',
                    'toolbar'=> 'full',
                    'media_upload' => true,
                ),
                array(
                    'key'   => 'field_more_about_image_top_2',
                    'label' => 'More About Top Image 2',
                    'name'  => 'more_about_image_top_2',
                    'type'  => 'image',
                    'instructions' => 'Upload the top image for the second More About Product section.',
                    'return_format' => 'url',
                ),
                array(
                    'key'   => 'field_more_about_image_bottom_2',
                    'label' => 'More About Bottom Image 2',
                    'name'  => 'more_about_image_bottom_2',
                    'type'  => 'image',
                    'instructions' => 'Upload the bottom image for the second More About Product section.',
                    'return_format' => 'url',
                ),
                // Add Reviews tab and fields
                array(
                    'key'   => 'tab_reviews',
                    'label' => 'Reviews',
                    'type'  => 'tab',
                    'placement' => 'top',
                ),
                array(
                    'key' => 'field_reviews_section_title',
                    'label' => 'Reviews Section Title',
                    'name' => 'reviews_section_title',
                    'type' => 'text',
                    'instructions' => 'Enter the heading for the Reviews section (displayed as H2)',
                    'default_value' => 'Reviews',
                ),
                array(
                    'key' => 'field_testimonial_1_text',
                    'label' => 'Testimonial 1 Text',
                    'name' => 'testimonial_1_text',
                    'type' => 'textarea',
                    'instructions' => 'Enter the text for the first testimonial.',
                ),
                array(
                    'key' => 'field_testimonial_1_author',
                    'label' => 'Testimonial 1 Author',
                    'name' => 'testimonial_1_author',
                    'type' => 'text',
                    'instructions' => 'Enter the author name for the first testimonial.',
                ),
                array(
                    'key' => 'field_testimonial_1_image',
                    'label' => 'Testimonial 1 Author Image',
                    'name' => 'testimonial_1_image',
                    'type' => 'image',
                    'instructions' => 'Upload the image for the first testimonial author.',
                    'return_format' => 'url',
                ),
                array(
                    'key' => 'field_testimonial_2_text',
                    'label' => 'Testimonial 2 Text',
                    'name' => 'testimonial_2_text',
                    'type' => 'textarea',
                    'instructions' => 'Enter the text for the second testimonial.',
                ),
                array(
                    'key' => 'field_testimonial_2_author',
                    'label' => 'Testimonial 2 Author',
                    'name' => 'testimonial_2_author',
                    'type' => 'text',
                    'instructions' => 'Enter the author name for the second testimonial.',
                ),
                array(
                    'key' => 'field_testimonial_2_image',
                    'label' => 'Testimonial 2 Author Image',
                    'name' => 'testimonial_2_image',
                    'type' => 'image',
                    'instructions' => 'Upload the image for the second testimonial author.',
                    'return_format' => 'url',
                ),
                array(
                    'key' => 'field_testimonial_3_text',
                    'label' => 'Testimonial 3 Text',
                    'name' => 'testimonial_3_text',
                    'type' => 'textarea',
                    'instructions' => 'Enter the text for the third testimonial.',
                ),
                array(
                    'key' => 'field_testimonial_3_author',
                    'label' => 'Testimonial 3 Author',
                    'name' => 'testimonial_3_author',
                    'type' => 'text',
                    'instructions' => 'Enter the author name for the third testimonial.',
                ),
                array(
                    'key' => 'field_testimonial_3_image',
                    'label' => 'Testimonial 3 Author Image',
                    'name' => 'testimonial_3_image',
                    'type' => 'image',
                    'instructions' => 'Upload the image for the third testimonial author.',
                    'return_format' => 'url',
                ),
                // Additional Testimonials (4-15)
                array(
                    'key' => 'field_testimonial_4_text',
                    'label' => 'Testimonial 4 Text',
                    'name' => 'testimonial_4_text',
                    'type' => 'textarea',
                    'instructions' => 'Enter the text for the fourth testimonial.',
                ),
                array(
                    'key' => 'field_testimonial_4_author',
                    'label' => 'Testimonial 4 Author',
                    'name' => 'testimonial_4_author',
                    'type' => 'text',
                    'instructions' => 'Enter the author name for the fourth testimonial.',
                ),
                array(
                    'key' => 'field_testimonial_4_image',
                    'label' => 'Testimonial 4 Author Image',
                    'name' => 'testimonial_4_image',
                    'type' => 'image',
                    'instructions' => 'Upload the image for the fourth testimonial author.',
                    'return_format' => 'url',
                ),
                array(
                    'key' => 'field_testimonial_5_text',
                    'label' => 'Testimonial 5 Text',
                    'name' => 'testimonial_5_text',
                    'type' => 'textarea',
                    'instructions' => 'Enter the text for the fifth testimonial.',
                ),
                array(
                    'key' => 'field_testimonial_5_author',
                    'label' => 'Testimonial 5 Author',
                    'name' => 'testimonial_5_author',
                    'type' => 'text',
                    'instructions' => 'Enter the author name for the fifth testimonial.',
                ),
                array(
                    'key' => 'field_testimonial_5_image',
                    'label' => 'Testimonial 5 Author Image',
                    'name' => 'testimonial_5_image',
                    'type' => 'image',
                    'instructions' => 'Upload the image for the fifth testimonial author.',
                    'return_format' => 'url',
                ),
                array(
                    'key' => 'field_testimonial_6_text',
                    'label' => 'Testimonial 6 Text',
                    'name' => 'testimonial_6_text',
                    'type' => 'textarea',
                    'instructions' => 'Enter the text for the sixth testimonial.',
                ),
                array(
                    'key' => 'field_testimonial_6_author',
                    'label' => 'Testimonial 6 Author',
                    'name' => 'testimonial_6_author',
                    'type' => 'text',
                    'instructions' => 'Enter the author name for the sixth testimonial.',
                ),
                array(
                    'key' => 'field_testimonial_6_image',
                    'label' => 'Testimonial 6 Author Image',
                    'name' => 'testimonial_6_image',
                    'type' => 'image',
                    'instructions' => 'Upload the image for the sixth testimonial author.',
                    'return_format' => 'url',
                ),
                array(
                    'key' => 'field_testimonial_7_text',
                    'label' => 'Testimonial 7 Text',
                    'name' => 'testimonial_7_text',
                    'type' => 'textarea',
                    'instructions' => 'Enter the text for the seventh testimonial.',
                ),
                array(
                    'key' => 'field_testimonial_7_author',
                    'label' => 'Testimonial 7 Author',
                    'name' => 'testimonial_7_author',
                    'type' => 'text',
                    'instructions' => 'Enter the author name for the seventh testimonial.',
                ),
                array(
                    'key' => 'field_testimonial_7_image',
                    'label' => 'Testimonial 7 Author Image',
                    'name' => 'testimonial_7_image',
                    'type' => 'image',
                    'instructions' => 'Upload the image for the seventh testimonial author.',
                    'return_format' => 'url',
                ),
                array(
                    'key' => 'field_testimonial_8_text',
                    'label' => 'Testimonial 8 Text',
                    'name' => 'testimonial_8_text',
                    'type' => 'textarea',
                    'instructions' => 'Enter the text for the eighth testimonial.',
                ),
                array(
                    'key' => 'field_testimonial_8_author',
                    'label' => 'Testimonial 8 Author',
                    'name' => 'testimonial_8_author',
                    'type' => 'text',
                    'instructions' => 'Enter the author name for the eighth testimonial.',
                ),
                array(
                    'key' => 'field_testimonial_8_image',
                    'label' => 'Testimonial 8 Author Image',
                    'name' => 'testimonial_8_image',
                    'type' => 'image',
                    'instructions' => 'Upload the image for the eighth testimonial author.',
                    'return_format' => 'url',
                ),
                array(
                    'key' => 'field_testimonial_9_text',
                    'label' => 'Testimonial 9 Text',
                    'name' => 'testimonial_9_text',
                    'type' => 'textarea',
                    'instructions' => 'Enter the text for the ninth testimonial.',
                ),
                array(
                    'key' => 'field_testimonial_9_author',
                    'label' => 'Testimonial 9 Author',
                    'name' => 'testimonial_9_author',
                    'type' => 'text',
                    'instructions' => 'Enter the author name for the ninth testimonial.',
                ),
                array(
                    'key' => 'field_testimonial_9_image',
                    'label' => 'Testimonial 9 Author Image',
                    'name' => 'testimonial_9_image',
                    'type' => 'image',
                    'instructions' => 'Upload the image for the ninth testimonial author.',
                    'return_format' => 'url',
                ),
                array(
                    'key' => 'field_testimonial_10_text',
                    'label' => 'Testimonial 10 Text',
                    'name' => 'testimonial_10_text',
                    'type' => 'textarea',
                    'instructions' => 'Enter the text for the tenth testimonial.',
                ),
                array(
                    'key' => 'field_testimonial_10_author',
                    'label' => 'Testimonial 10 Author',
                    'name' => 'testimonial_10_author',
                    'type' => 'text',
                    'instructions' => 'Enter the author name for the tenth testimonial.',
                ),
                array(
                    'key' => 'field_testimonial_10_image',
                    'label' => 'Testimonial 10 Author Image',
                    'name' => 'testimonial_10_image',
                    'type' => 'image',
                    'instructions' => 'Upload the image for the tenth testimonial author.',
                    'return_format' => 'url',
                ),
                array(
                    'key' => 'field_testimonial_11_text',
                    'label' => 'Testimonial 11 Text',
                    'name' => 'testimonial_11_text',
                    'type' => 'textarea',
                    'instructions' => 'Enter the text for the eleventh testimonial.',
                ),
                array(
                    'key' => 'field_testimonial_11_author',
                    'label' => 'Testimonial 11 Author',
                    'name' => 'testimonial_11_author',
                    'type' => 'text',
                    'instructions' => 'Enter the author name for the eleventh testimonial.',
                ),
                array(
                    'key' => 'field_testimonial_11_image',
                    'label' => 'Testimonial 11 Author Image',
                    'name' => 'testimonial_11_image',
                    'type' => 'image',
                    'instructions' => 'Upload the image for the eleventh testimonial author.',
                    'return_format' => 'url',
                ),
                array(
                    'key' => 'field_testimonial_12_text',
                    'label' => 'Testimonial 12 Text',
                    'name' => 'testimonial_12_text',
                    'type' => 'textarea',
                    'instructions' => 'Enter the text for the twelfth testimonial.',
                ),
                array(
                    'key' => 'field_testimonial_12_author',
                    'label' => 'Testimonial 12 Author',
                    'name' => 'testimonial_12_author',
                    'type' => 'text',
                    'instructions' => 'Enter the author name for the twelfth testimonial.',
                ),
                array(
                    'key' => 'field_testimonial_12_image',
                    'label' => 'Testimonial 12 Author Image',
                    'name' => 'testimonial_12_image',
                    'type' => 'image',
                    'instructions' => 'Upload the image for the twelfth testimonial author.',
                    'return_format' => 'url',
                ),
                array(
                    'key' => 'field_testimonial_13_text',
                    'label' => 'Testimonial 13 Text',
                    'name' => 'testimonial_13_text',
                    'type' => 'textarea',
                    'instructions' => 'Enter the text for the thirteenth testimonial.',
                ),
                array(
                    'key' => 'field_testimonial_13_author',
                    'label' => 'Testimonial 13 Author',
                    'name' => 'testimonial_13_author',
                    'type' => 'text',
                    'instructions' => 'Enter the author name for the thirteenth testimonial.',
                ),
                array(
                    'key' => 'field_testimonial_13_image',
                    'label' => 'Testimonial 13 Author Image',
                    'name' => 'testimonial_13_image',
                    'type' => 'image',
                    'instructions' => 'Upload the image for the thirteenth testimonial author.',
                    'return_format' => 'url',
                ),
                array(
                    'key' => 'field_testimonial_14_text',
                    'label' => 'Testimonial 14 Text',
                    'name' => 'testimonial_14_text',
                    'type' => 'textarea',
                    'instructions' => 'Enter the text for the fourteenth testimonial.',
                ),
                array(
                    'key' => 'field_testimonial_14_author',
                    'label' => 'Testimonial 14 Author',
                    'name' => 'testimonial_14_author',
                    'type' => 'text',
                    'instructions' => 'Enter the author name for the fourteenth testimonial.',
                ),
                array(
                    'key' => 'field_testimonial_14_image',
                    'label' => 'Testimonial 14 Author Image',
                    'name' => 'testimonial_14_image',
                    'type' => 'image',
                    'instructions' => 'Upload the image for the fourteenth testimonial author.',
                    'return_format' => 'url',
                ),
                array(
                    'key' => 'field_testimonial_15_text',
                    'label' => 'Testimonial 15 Text',
                    'name' => 'testimonial_15_text',
                    'type' => 'textarea',
                    'instructions' => 'Enter the text for the fifteenth testimonial.',
                ),
                array(
                    'key' => 'field_testimonial_15_author',
                    'label' => 'Testimonial 15 Author',
                    'name' => 'testimonial_15_author',
                    'type' => 'text',
                    'instructions' => 'Enter the author name for the fifteenth testimonial.',
                ),
                array(
                    'key' => 'field_testimonial_15_image',
                    'label' => 'Testimonial 15 Author Image',
                    'name' => 'testimonial_15_image',
                    'type' => 'image',
                    'instructions' => 'Upload the image for the fifteenth testimonial author.',
                    'return_format' => 'url',
                ),
                // Additional Testimonials (16-24)
                array(
                    'key' => 'field_testimonial_16_text',
                    'label' => 'Testimonial 16 Text',
                    'name' => 'testimonial_16_text',
                    'type' => 'textarea',
                    'instructions' => 'Enter the text for the sixteenth testimonial.',
                ),
                array(
                    'key' => 'field_testimonial_16_author',
                    'label' => 'Testimonial 16 Author',
                    'name' => 'testimonial_16_author',
                    'type' => 'text',
                    'instructions' => 'Enter the author name for the sixteenth testimonial.',
                ),
                array(
                    'key' => 'field_testimonial_16_image',
                    'label' => 'Testimonial 16 Author Image',
                    'name' => 'testimonial_16_image',
                    'type' => 'image',
                    'instructions' => 'Upload the image for the sixteenth testimonial author.',
                    'return_format' => 'url',
                ),
                array(
                    'key' => 'field_testimonial_17_text',
                    'label' => 'Testimonial 17 Text',
                    'name' => 'testimonial_17_text',
                    'type' => 'textarea',
                    'instructions' => 'Enter the text for the seventeenth testimonial.',
                ),
                array(
                    'key' => 'field_testimonial_17_author',
                    'label' => 'Testimonial 17 Author',
                    'name' => 'testimonial_17_author',
                    'type' => 'text',
                    'instructions' => 'Enter the author name for the seventeenth testimonial.',
                ),
                array(
                    'key' => 'field_testimonial_17_image',
                    'label' => 'Testimonial 17 Author Image',
                    'name' => 'testimonial_17_image',
                    'type' => 'image',
                    'instructions' => 'Upload the image for the seventeenth testimonial author.',
                    'return_format' => 'url',
                ),
                array(
                    'key' => 'field_testimonial_18_text',
                    'label' => 'Testimonial 18 Text',
                    'name' => 'testimonial_18_text',
                    'type' => 'textarea',
                    'instructions' => 'Enter the text for the eighteenth testimonial.',
                ),
                array(
                    'key' => 'field_testimonial_18_author',
                    'label' => 'Testimonial 18 Author',
                    'name' => 'testimonial_18_author',
                    'type' => 'text',
                    'instructions' => 'Enter the author name for the eighteenth testimonial.',
                ),
                array(
                    'key' => 'field_testimonial_18_image',
                    'label' => 'Testimonial 18 Author Image',
                    'name' => 'testimonial_18_image',
                    'type' => 'image',
                    'instructions' => 'Upload the image for the eighteenth testimonial author.',
                    'return_format' => 'url',
                ),
                array(
                    'key' => 'field_testimonial_19_text',
                    'label' => 'Testimonial 19 Text',
                    'name' => 'testimonial_19_text',
                    'type' => 'textarea',
                    'instructions' => 'Enter the text for the nineteenth testimonial.',
                ),
                array(
                    'key' => 'field_testimonial_19_author',
                    'label' => 'Testimonial 19 Author',
                    'name' => 'testimonial_19_author',
                    'type' => 'text',
                    'instructions' => 'Enter the author name for the nineteenth testimonial.',
                ),
                array(
                    'key' => 'field_testimonial_19_image',
                    'label' => 'Testimonial 19 Author Image',
                    'name' => 'testimonial_19_image',
                    'type' => 'image',
                    'instructions' => 'Upload the image for the nineteenth testimonial author.',
                    'return_format' => 'url',
                ),
                array(
                    'key' => 'field_testimonial_20_text',
                    'label' => 'Testimonial 20 Text',
                    'name' => 'testimonial_20_text',
                    'type' => 'textarea',
                    'instructions' => 'Enter the text for the twentieth testimonial.',
                ),
                array(
                    'key' => 'field_testimonial_20_author',
                    'label' => 'Testimonial 20 Author',
                    'name' => 'testimonial_20_author',
                    'type' => 'text',
                    'instructions' => 'Enter the author name for the twentieth testimonial.',
                ),
                array(
                    'key' => 'field_testimonial_20_image',
                    'label' => 'Testimonial 20 Author Image',
                    'name' => 'testimonial_20_image',
                    'type' => 'image',
                    'instructions' => 'Upload the image for the twentieth testimonial author.',
                    'return_format' => 'url',
                ),
                array(
                    'key' => 'field_testimonial_21_text',
                    'label' => 'Testimonial 21 Text',
                    'name' => 'testimonial_21_text',
                    'type' => 'textarea',
                    'instructions' => 'Enter the text for the twenty-first testimonial.',
                ),
                array(
                    'key' => 'field_testimonial_21_author',
                    'label' => 'Testimonial 21 Author',
                    'name' => 'testimonial_21_author',
                    'type' => 'text',
                    'instructions' => 'Enter the author name for the twenty-first testimonial.',
                ),
                array(
                    'key' => 'field_testimonial_21_image',
                    'label' => 'Testimonial 21 Author Image',
                    'name' => 'testimonial_21_image',
                    'type' => 'image',
                    'instructions' => 'Upload the image for the twenty-first testimonial author.',
                    'return_format' => 'url',
                ),
                array(
                    'key' => 'field_testimonial_22_text',
                    'label' => 'Testimonial 22 Text',
                    'name' => 'testimonial_22_text',
                    'type' => 'textarea',
                    'instructions' => 'Enter the text for the twenty-second testimonial.',
                ),
                array(
                    'key' => 'field_testimonial_22_author',
                    'label' => 'Testimonial 22 Author',
                    'name' => 'testimonial_22_author',
                    'type' => 'text',
                    'instructions' => 'Enter the author name for the twenty-second testimonial.',
                ),
                array(
                    'key' => 'field_testimonial_22_image',
                    'label' => 'Testimonial 22 Author Image',
                    'name' => 'testimonial_22_image',
                    'type' => 'image',
                    'instructions' => 'Upload the image for the twenty-second testimonial author.',
                    'return_format' => 'url',
                ),
                array(
                    'key' => 'field_testimonial_23_text',
                    'label' => 'Testimonial 23 Text',
                    'name' => 'testimonial_23_text',
                    'type' => 'textarea',
                    'instructions' => 'Enter the text for the twenty-third testimonial.',
                ),
                array(
                    'key' => 'field_testimonial_23_author',
                    'label' => 'Testimonial 23 Author',
                    'name' => 'testimonial_23_author',
                    'type' => 'text',
                    'instructions' => 'Enter the author name for the twenty-third testimonial.',
                ),
                array(
                    'key' => 'field_testimonial_23_image',
                    'label' => 'Testimonial 23 Author Image',
                    'name' => 'testimonial_23_image',
                    'type' => 'image',
                    'instructions' => 'Upload the image for the twenty-third testimonial author.',
                    'return_format' => 'url',
                ),
                array(
                    'key' => 'field_testimonial_24_text',
                    'label' => 'Testimonial 24 Text',
                    'name' => 'testimonial_24_text',
                    'type' => 'textarea',
                    'instructions' => 'Enter the text for the twenty-fourth testimonial.',
                ),
                array(
                    'key' => 'field_testimonial_24_author',
                    'label' => 'Testimonial 24 Author',
                    'name' => 'testimonial_24_author',
                    'type' => 'text',
                    'instructions' => 'Enter the author name for the twenty-fourth testimonial.',
                ),
                array(
                    'key' => 'field_testimonial_24_image',
                    'label' => 'Testimonial 24 Author Image',
                    'name' => 'testimonial_24_image',
                    'type' => 'image',
                    'instructions' => 'Upload the image for the twenty-fourth testimonial author.',
                    'return_format' => 'url',
                ),
                // Add FAQs tab and fields
                array(
                    'key'   => 'tab_faqs',
                    'label' => 'FAQs',
                    'type'  => 'tab',
                    'placement' => 'top',
                ),
                // FAQ Section Title
                array(
                    'key' => 'field_faq_section_title',
                    'label' => 'FAQ Section Title',
                    'name' => 'faq_section_title',
                    'type' => 'text',
                    'instructions' => 'Enter the title for the FAQ section (displayed as H2)',
                    'default_value' => 'Frequently Asked Questions',
                ),
                // FAQ Questions and Answers (1-6)
                array(
                    'key' => 'field_faq_question_1',
                    'label' => 'Question 1',
                    'name' => 'faq_question_1',
                    'type' => 'text',
                    'instructions' => 'Enter the first FAQ question.',
                ),
                array(
                    'key' => 'field_faq_answer_1',
                    'label' => 'Answer 1',
                    'name' => 'faq_answer_1',
                    'type' => 'textarea',
                    'instructions' => 'Enter the answer for the first FAQ question.',
                ),
                array(
                    'key' => 'field_faq_question_2', 'label' => 'Question 2', 'name' => 'faq_question_2', 'type' => 'text', 'instructions' => 'Enter the second FAQ question.',
                ),
                array(
                    'key' => 'field_faq_answer_2', 'label' => 'Answer 2', 'name' => 'faq_answer_2', 'type' => 'textarea', 'instructions' => 'Enter the answer for the second FAQ question.',
                ),
                array('key' => 'field_faq_question_3', 'label' => 'Question 3', 'name' => 'faq_question_3', 'type' => 'text', 'instructions' => 'Enter the third FAQ question.'),
                array('key' => 'field_faq_answer_3', 'label' => 'Answer 3', 'name' => 'faq_answer_3', 'type' => 'textarea', 'instructions' => 'Enter the answer for the third FAQ question.'),
                array('key' => 'field_faq_question_4', 'label' => 'Question 4', 'name' => 'faq_question_4', 'type' => 'text', 'instructions' => 'Enter the fourth FAQ question.'),
                array('key' => 'field_faq_answer_4', 'label' => 'Answer 4', 'name' => 'faq_answer_4', 'type' => 'textarea', 'instructions' => 'Enter the answer for the fourth FAQ question.'),
                array('key' => 'field_faq_question_5', 'label' => 'Question 5', 'name' => 'faq_question_5', 'type' => 'text', 'instructions' => 'Enter the fifth FAQ question.'),
                array('key' => 'field_faq_answer_5', 'label' => 'Answer 5', 'name' => 'faq_answer_5', 'type' => 'textarea', 'instructions' => 'Enter the answer for the fifth FAQ question.'),
                array('key' => 'field_faq_question_6', 'label' => 'Question 6', 'name' => 'faq_question_6', 'type' => 'text', 'instructions' => 'Enter the sixth FAQ question.'),
                array('key' => 'field_faq_answer_6', 'label' => 'Answer 6', 'name' => 'faq_answer_6', 'type' => 'textarea', 'instructions' => 'Enter the answer for the sixth FAQ question.'),
                
                // Add Footer tab and fields
                array(
                    'key'   => 'tab_footer',
                    'label' => 'Footer',
                    'type'  => 'tab',
                    'placement' => 'top',
                ),
                array(
                    'key'           => 'field_footer_disclaimer_1',
                    'label'         => 'Disclaimer 1',
                    'name'          => 'footer_disclaimer_1',
                    'type'          => 'textarea',
                    'instructions'  => 'Enter the disclaimer text to display on the left side of the footer.',
                ),
                array(
                    'key'           => 'field_footer_disclaimer_2',
                    'label'         => 'Disclaimer 2',
                    'name'          => 'footer_disclaimer_2',
                    'type'          => 'textarea',
                    'instructions'  => 'Enter the disclaimer text to display on the right side of the footer.',
                ),
                array(
                    'key'           => 'field_terms_url',
                    'label'         => 'Terms of Use URL',
                    'name'          => 'terms_url',
                    'type'          => 'url',
                    'instructions'  => 'Enter the URL for Terms of Use page.',
                ),
                array(
                    'key'           => 'field_privacy_url',
                    'label'         => 'Privacy Policy URL',
                    'name'          => 'privacy_url',
                    'type'          => 'url',
                    'instructions'  => 'Enter the URL for Privacy Policy page.',
                ),
                array(
                    'key'           => 'field_support_email',
                    'label'         => 'Support Email',
                    'name'          => 'support_email',
                    'type'          => 'email',
                    'instructions'  => 'Enter the email address for customer support.',
                ),
                
                // Add Sticky CTA tab and fields
                array(
                    'key'   => 'tab_sticky_cta',
                    'label' => 'Sticky CTA',
                    'type'  => 'tab',
                    'placement' => 'top',
                ),
                array(
                    'key'           => 'field_sticky_cta_text',
                    'label'         => 'Strong Call To Action Text',
                    'name'          => 'sticky_cta_text',
                    'type'          => 'text',
                    'instructions'  => 'Enter the strong call to action text for the sticky element.',
                ),
                array(
                    'key'           => 'field_sticky_button_text',
                    'label'         => 'Button Text',
                    'name'          => 'sticky_button_text',
                    'type'          => 'text',
                    'instructions'  => 'Enter the text for the sticky CTA button.',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'page_template',
                        'operator' => '==',
                        'value' => 'one-pager-template.php',
                    ),
                ),
            ),
        ));
    }
}
add_action('acf/init', 'opalp_register_custom_fields');